@startuml View single coworking space (GET)

header Co-working Space Sequence Diagram
footer Page %page% of %lastpage%
title "View single coworking space (GET)"

participant "User" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:coworkingSpaces" as routerCoworkingSpaces
participant "<<controllers>>\n:coworkingSpaces" as controllersCoworkingSpaces
participant "<<model>>\n:CoworkingSpace" as modelCoworkingSpace
database "<<MongoDB>>\n:coworkingSpaces" as coworkingSpacesDatabase

client->server ++:req.get('/coworkingSpaces/:id')
server->routerCoworkingSpaces ++:app.use('/coworkingSpaces',coworkingSpaces)
routerCoworkingSpaces -> controllersCoworkingSpaces ++:getCoworkingSpace()
controllersCoworkingSpaces->modelCoworkingSpace ++:findById(req.params.id)
modelCoworkingSpace ->coworkingSpacesDatabase ++: coworkingSpaceSchema
coworkingSpacesDatabase --> modelCoworkingSpace --: coworkingSpace
controllersCoworkingSpaces <-- modelCoworkingSpace --:coworkingSpace
controllersCoworkingSpaces->client --:response

@enduml