@startuml View all coworking space (GET)

header Co-working Space Sequence Diagram
footer Page %page% of %lastpage%
title "View all coworking space (GET)"

participant "User" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:coworkingSpaces" as routerCoworkingSpaces
participant "<<controllers>>\n:coworkingSpaces" as controllersCoworkingSpaces
participant "<<model>>\n:CoworkingSpace" as modelCoworkingSpace
database "<<MongoDB>>\n:coworkingSpaces" as coworkingSpacesDatabase

client->server ++:req.get('/coworkingSpaces')
server->routerCoworkingSpaces ++:app.use('/coworkingSpaces',coworkingSpaces)
routerCoworkingSpaces -> controllersCoworkingSpaces ++:getCoworkingSpaces()
controllersCoworkingSpaces->modelCoworkingSpace ++:find()
modelCoworkingSpace ->coworkingSpacesDatabase ++: coworkingSpaceSchema
coworkingSpacesDatabase --> modelCoworkingSpace --: coworkingSpaces
controllersCoworkingSpaces <-- modelCoworkingSpace --:coworkingSpaces
controllersCoworkingSpaces->client --:response

@enduml